################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
CPP_SRCS += \
../lib/dlib/test/active_learning.cpp \
../lib/dlib/test/any.cpp \
../lib/dlib/test/any_function.cpp \
../lib/dlib/test/array.cpp \
../lib/dlib/test/array2d.cpp \
../lib/dlib/test/assignment_learning.cpp \
../lib/dlib/test/base64.cpp \
../lib/dlib/test/bayes_nets.cpp \
../lib/dlib/test/bigint.cpp \
../lib/dlib/test/binary_search_tree_kernel_1a.cpp \
../lib/dlib/test/binary_search_tree_kernel_2a.cpp \
../lib/dlib/test/binary_search_tree_mm1.cpp \
../lib/dlib/test/binary_search_tree_mm2.cpp \
../lib/dlib/test/bridge.cpp \
../lib/dlib/test/bsp.cpp \
../lib/dlib/test/byte_orderer.cpp \
../lib/dlib/test/cca.cpp \
../lib/dlib/test/clustering.cpp \
../lib/dlib/test/cmd_line_parser.cpp \
../lib/dlib/test/cmd_line_parser_wchar_t.cpp \
../lib/dlib/test/compress_stream.cpp \
../lib/dlib/test/conditioning_class.cpp \
../lib/dlib/test/conditioning_class_c.cpp \
../lib/dlib/test/config_reader.cpp \
../lib/dlib/test/correlation_tracker.cpp \
../lib/dlib/test/crc32.cpp \
../lib/dlib/test/create_iris_datafile.cpp \
../lib/dlib/test/cublas.cpp \
../lib/dlib/test/data_io.cpp \
../lib/dlib/test/directed_graph.cpp \
../lib/dlib/test/discriminant_pca.cpp \
../lib/dlib/test/disjoint_subsets.cpp \
../lib/dlib/test/dnn.cpp \
../lib/dlib/test/ekm_and_lisf.cpp \
../lib/dlib/test/elastic_net.cpp \
../lib/dlib/test/empirical_kernel_map.cpp \
../lib/dlib/test/entropy_coder.cpp \
../lib/dlib/test/entropy_encoder_model.cpp \
../lib/dlib/test/example.cpp \
../lib/dlib/test/example_args.cpp \
../lib/dlib/test/face.cpp \
../lib/dlib/test/fft.cpp \
../lib/dlib/test/fhog.cpp \
../lib/dlib/test/filtering.cpp \
../lib/dlib/test/find_max_factor_graph_nmplp.cpp \
../lib/dlib/test/find_max_factor_graph_viterbi.cpp \
../lib/dlib/test/find_optimal_parameters.cpp \
../lib/dlib/test/geometry.cpp \
../lib/dlib/test/graph.cpp \
../lib/dlib/test/graph_cuts.cpp \
../lib/dlib/test/graph_labeler.cpp \
../lib/dlib/test/hash.cpp \
../lib/dlib/test/hash_map.cpp \
../lib/dlib/test/hash_set.cpp \
../lib/dlib/test/hash_table.cpp \
../lib/dlib/test/hog_image.cpp \
../lib/dlib/test/image.cpp \
../lib/dlib/test/iosockstream.cpp \
../lib/dlib/test/is_same_object.cpp \
../lib/dlib/test/kcentroid.cpp \
../lib/dlib/test/kernel_matrix.cpp \
../lib/dlib/test/kmeans.cpp \
../lib/dlib/test/learning_to_track.cpp \
../lib/dlib/test/least_squares.cpp \
../lib/dlib/test/linear_manifold_regularizer.cpp \
../lib/dlib/test/lspi.cpp \
../lib/dlib/test/lz77_buffer.cpp \
../lib/dlib/test/main.cpp \
../lib/dlib/test/map.cpp \
../lib/dlib/test/matrix.cpp \
../lib/dlib/test/matrix2.cpp \
../lib/dlib/test/matrix3.cpp \
../lib/dlib/test/matrix4.cpp \
../lib/dlib/test/matrix_chol.cpp \
../lib/dlib/test/matrix_eig.cpp \
../lib/dlib/test/matrix_lu.cpp \
../lib/dlib/test/matrix_qr.cpp \
../lib/dlib/test/max_cost_assignment.cpp \
../lib/dlib/test/max_sum_submatrix.cpp \
../lib/dlib/test/md5.cpp \
../lib/dlib/test/member_function_pointer.cpp \
../lib/dlib/test/metaprogramming.cpp \
../lib/dlib/test/mpc.cpp \
../lib/dlib/test/multithreaded_object.cpp \
../lib/dlib/test/numerical_integration.cpp \
../lib/dlib/test/object_detector.cpp \
../lib/dlib/test/oca.cpp \
../lib/dlib/test/one_vs_all_trainer.cpp \
../lib/dlib/test/one_vs_one_trainer.cpp \
../lib/dlib/test/opt_qp_solver.cpp \
../lib/dlib/test/optimization.cpp \
../lib/dlib/test/optimization_test_functions.cpp \
../lib/dlib/test/parallel_for.cpp \
../lib/dlib/test/parse.cpp \
../lib/dlib/test/pipe.cpp \
../lib/dlib/test/pixel.cpp \
../lib/dlib/test/probabilistic.cpp \
../lib/dlib/test/pyramid_down.cpp \
../lib/dlib/test/queue.cpp \
../lib/dlib/test/rand.cpp \
../lib/dlib/test/ranking.cpp \
../lib/dlib/test/read_write_mutex.cpp \
../lib/dlib/test/reference_counter.cpp \
../lib/dlib/test/rls.cpp \
../lib/dlib/test/sammon.cpp \
../lib/dlib/test/scan_image.cpp \
../lib/dlib/test/sequence.cpp \
../lib/dlib/test/sequence_labeler.cpp \
../lib/dlib/test/sequence_segmenter.cpp \
../lib/dlib/test/serialize.cpp \
../lib/dlib/test/set.cpp \
../lib/dlib/test/sldf.cpp \
../lib/dlib/test/sliding_buffer.cpp \
../lib/dlib/test/smart_pointers.cpp \
../lib/dlib/test/sockets.cpp \
../lib/dlib/test/sockets2.cpp \
../lib/dlib/test/sockstreambuf.cpp \
../lib/dlib/test/sparse_vector.cpp \
../lib/dlib/test/stack.cpp \
../lib/dlib/test/static_map.cpp \
../lib/dlib/test/static_set.cpp \
../lib/dlib/test/statistics.cpp \
../lib/dlib/test/std_vector_c.cpp \
../lib/dlib/test/string.cpp \
../lib/dlib/test/svm.cpp \
../lib/dlib/test/svm_c_linear.cpp \
../lib/dlib/test/svm_c_linear_dcd.cpp \
../lib/dlib/test/svm_multiclass_linear.cpp \
../lib/dlib/test/svm_struct.cpp \
../lib/dlib/test/svr_linear_trainer.cpp \
../lib/dlib/test/symmetric_matrix_cache.cpp \
../lib/dlib/test/tester.cpp \
../lib/dlib/test/thread_pool.cpp \
../lib/dlib/test/threads.cpp \
../lib/dlib/test/timer.cpp \
../lib/dlib/test/tokenizer.cpp \
../lib/dlib/test/trust_region.cpp \
../lib/dlib/test/tuple.cpp \
../lib/dlib/test/type_safe_union.cpp \
../lib/dlib/test/vectorstream.cpp 

OBJS += \
./lib/dlib/test/active_learning.o \
./lib/dlib/test/any.o \
./lib/dlib/test/any_function.o \
./lib/dlib/test/array.o \
./lib/dlib/test/array2d.o \
./lib/dlib/test/assignment_learning.o \
./lib/dlib/test/base64.o \
./lib/dlib/test/bayes_nets.o \
./lib/dlib/test/bigint.o \
./lib/dlib/test/binary_search_tree_kernel_1a.o \
./lib/dlib/test/binary_search_tree_kernel_2a.o \
./lib/dlib/test/binary_search_tree_mm1.o \
./lib/dlib/test/binary_search_tree_mm2.o \
./lib/dlib/test/bridge.o \
./lib/dlib/test/bsp.o \
./lib/dlib/test/byte_orderer.o \
./lib/dlib/test/cca.o \
./lib/dlib/test/clustering.o \
./lib/dlib/test/cmd_line_parser.o \
./lib/dlib/test/cmd_line_parser_wchar_t.o \
./lib/dlib/test/compress_stream.o \
./lib/dlib/test/conditioning_class.o \
./lib/dlib/test/conditioning_class_c.o \
./lib/dlib/test/config_reader.o \
./lib/dlib/test/correlation_tracker.o \
./lib/dlib/test/crc32.o \
./lib/dlib/test/create_iris_datafile.o \
./lib/dlib/test/cublas.o \
./lib/dlib/test/data_io.o \
./lib/dlib/test/directed_graph.o \
./lib/dlib/test/discriminant_pca.o \
./lib/dlib/test/disjoint_subsets.o \
./lib/dlib/test/dnn.o \
./lib/dlib/test/ekm_and_lisf.o \
./lib/dlib/test/elastic_net.o \
./lib/dlib/test/empirical_kernel_map.o \
./lib/dlib/test/entropy_coder.o \
./lib/dlib/test/entropy_encoder_model.o \
./lib/dlib/test/example.o \
./lib/dlib/test/example_args.o \
./lib/dlib/test/face.o \
./lib/dlib/test/fft.o \
./lib/dlib/test/fhog.o \
./lib/dlib/test/filtering.o \
./lib/dlib/test/find_max_factor_graph_nmplp.o \
./lib/dlib/test/find_max_factor_graph_viterbi.o \
./lib/dlib/test/find_optimal_parameters.o \
./lib/dlib/test/geometry.o \
./lib/dlib/test/graph.o \
./lib/dlib/test/graph_cuts.o \
./lib/dlib/test/graph_labeler.o \
./lib/dlib/test/hash.o \
./lib/dlib/test/hash_map.o \
./lib/dlib/test/hash_set.o \
./lib/dlib/test/hash_table.o \
./lib/dlib/test/hog_image.o \
./lib/dlib/test/image.o \
./lib/dlib/test/iosockstream.o \
./lib/dlib/test/is_same_object.o \
./lib/dlib/test/kcentroid.o \
./lib/dlib/test/kernel_matrix.o \
./lib/dlib/test/kmeans.o \
./lib/dlib/test/learning_to_track.o \
./lib/dlib/test/least_squares.o \
./lib/dlib/test/linear_manifold_regularizer.o \
./lib/dlib/test/lspi.o \
./lib/dlib/test/lz77_buffer.o \
./lib/dlib/test/main.o \
./lib/dlib/test/map.o \
./lib/dlib/test/matrix.o \
./lib/dlib/test/matrix2.o \
./lib/dlib/test/matrix3.o \
./lib/dlib/test/matrix4.o \
./lib/dlib/test/matrix_chol.o \
./lib/dlib/test/matrix_eig.o \
./lib/dlib/test/matrix_lu.o \
./lib/dlib/test/matrix_qr.o \
./lib/dlib/test/max_cost_assignment.o \
./lib/dlib/test/max_sum_submatrix.o \
./lib/dlib/test/md5.o \
./lib/dlib/test/member_function_pointer.o \
./lib/dlib/test/metaprogramming.o \
./lib/dlib/test/mpc.o \
./lib/dlib/test/multithreaded_object.o \
./lib/dlib/test/numerical_integration.o \
./lib/dlib/test/object_detector.o \
./lib/dlib/test/oca.o \
./lib/dlib/test/one_vs_all_trainer.o \
./lib/dlib/test/one_vs_one_trainer.o \
./lib/dlib/test/opt_qp_solver.o \
./lib/dlib/test/optimization.o \
./lib/dlib/test/optimization_test_functions.o \
./lib/dlib/test/parallel_for.o \
./lib/dlib/test/parse.o \
./lib/dlib/test/pipe.o \
./lib/dlib/test/pixel.o \
./lib/dlib/test/probabilistic.o \
./lib/dlib/test/pyramid_down.o \
./lib/dlib/test/queue.o \
./lib/dlib/test/rand.o \
./lib/dlib/test/ranking.o \
./lib/dlib/test/read_write_mutex.o \
./lib/dlib/test/reference_counter.o \
./lib/dlib/test/rls.o \
./lib/dlib/test/sammon.o \
./lib/dlib/test/scan_image.o \
./lib/dlib/test/sequence.o \
./lib/dlib/test/sequence_labeler.o \
./lib/dlib/test/sequence_segmenter.o \
./lib/dlib/test/serialize.o \
./lib/dlib/test/set.o \
./lib/dlib/test/sldf.o \
./lib/dlib/test/sliding_buffer.o \
./lib/dlib/test/smart_pointers.o \
./lib/dlib/test/sockets.o \
./lib/dlib/test/sockets2.o \
./lib/dlib/test/sockstreambuf.o \
./lib/dlib/test/sparse_vector.o \
./lib/dlib/test/stack.o \
./lib/dlib/test/static_map.o \
./lib/dlib/test/static_set.o \
./lib/dlib/test/statistics.o \
./lib/dlib/test/std_vector_c.o \
./lib/dlib/test/string.o \
./lib/dlib/test/svm.o \
./lib/dlib/test/svm_c_linear.o \
./lib/dlib/test/svm_c_linear_dcd.o \
./lib/dlib/test/svm_multiclass_linear.o \
./lib/dlib/test/svm_struct.o \
./lib/dlib/test/svr_linear_trainer.o \
./lib/dlib/test/symmetric_matrix_cache.o \
./lib/dlib/test/tester.o \
./lib/dlib/test/thread_pool.o \
./lib/dlib/test/threads.o \
./lib/dlib/test/timer.o \
./lib/dlib/test/tokenizer.o \
./lib/dlib/test/trust_region.o \
./lib/dlib/test/tuple.o \
./lib/dlib/test/type_safe_union.o \
./lib/dlib/test/vectorstream.o 

CPP_DEPS += \
./lib/dlib/test/active_learning.d \
./lib/dlib/test/any.d \
./lib/dlib/test/any_function.d \
./lib/dlib/test/array.d \
./lib/dlib/test/array2d.d \
./lib/dlib/test/assignment_learning.d \
./lib/dlib/test/base64.d \
./lib/dlib/test/bayes_nets.d \
./lib/dlib/test/bigint.d \
./lib/dlib/test/binary_search_tree_kernel_1a.d \
./lib/dlib/test/binary_search_tree_kernel_2a.d \
./lib/dlib/test/binary_search_tree_mm1.d \
./lib/dlib/test/binary_search_tree_mm2.d \
./lib/dlib/test/bridge.d \
./lib/dlib/test/bsp.d \
./lib/dlib/test/byte_orderer.d \
./lib/dlib/test/cca.d \
./lib/dlib/test/clustering.d \
./lib/dlib/test/cmd_line_parser.d \
./lib/dlib/test/cmd_line_parser_wchar_t.d \
./lib/dlib/test/compress_stream.d \
./lib/dlib/test/conditioning_class.d \
./lib/dlib/test/conditioning_class_c.d \
./lib/dlib/test/config_reader.d \
./lib/dlib/test/correlation_tracker.d \
./lib/dlib/test/crc32.d \
./lib/dlib/test/create_iris_datafile.d \
./lib/dlib/test/cublas.d \
./lib/dlib/test/data_io.d \
./lib/dlib/test/directed_graph.d \
./lib/dlib/test/discriminant_pca.d \
./lib/dlib/test/disjoint_subsets.d \
./lib/dlib/test/dnn.d \
./lib/dlib/test/ekm_and_lisf.d \
./lib/dlib/test/elastic_net.d \
./lib/dlib/test/empirical_kernel_map.d \
./lib/dlib/test/entropy_coder.d \
./lib/dlib/test/entropy_encoder_model.d \
./lib/dlib/test/example.d \
./lib/dlib/test/example_args.d \
./lib/dlib/test/face.d \
./lib/dlib/test/fft.d \
./lib/dlib/test/fhog.d \
./lib/dlib/test/filtering.d \
./lib/dlib/test/find_max_factor_graph_nmplp.d \
./lib/dlib/test/find_max_factor_graph_viterbi.d \
./lib/dlib/test/find_optimal_parameters.d \
./lib/dlib/test/geometry.d \
./lib/dlib/test/graph.d \
./lib/dlib/test/graph_cuts.d \
./lib/dlib/test/graph_labeler.d \
./lib/dlib/test/hash.d \
./lib/dlib/test/hash_map.d \
./lib/dlib/test/hash_set.d \
./lib/dlib/test/hash_table.d \
./lib/dlib/test/hog_image.d \
./lib/dlib/test/image.d \
./lib/dlib/test/iosockstream.d \
./lib/dlib/test/is_same_object.d \
./lib/dlib/test/kcentroid.d \
./lib/dlib/test/kernel_matrix.d \
./lib/dlib/test/kmeans.d \
./lib/dlib/test/learning_to_track.d \
./lib/dlib/test/least_squares.d \
./lib/dlib/test/linear_manifold_regularizer.d \
./lib/dlib/test/lspi.d \
./lib/dlib/test/lz77_buffer.d \
./lib/dlib/test/main.d \
./lib/dlib/test/map.d \
./lib/dlib/test/matrix.d \
./lib/dlib/test/matrix2.d \
./lib/dlib/test/matrix3.d \
./lib/dlib/test/matrix4.d \
./lib/dlib/test/matrix_chol.d \
./lib/dlib/test/matrix_eig.d \
./lib/dlib/test/matrix_lu.d \
./lib/dlib/test/matrix_qr.d \
./lib/dlib/test/max_cost_assignment.d \
./lib/dlib/test/max_sum_submatrix.d \
./lib/dlib/test/md5.d \
./lib/dlib/test/member_function_pointer.d \
./lib/dlib/test/metaprogramming.d \
./lib/dlib/test/mpc.d \
./lib/dlib/test/multithreaded_object.d \
./lib/dlib/test/numerical_integration.d \
./lib/dlib/test/object_detector.d \
./lib/dlib/test/oca.d \
./lib/dlib/test/one_vs_all_trainer.d \
./lib/dlib/test/one_vs_one_trainer.d \
./lib/dlib/test/opt_qp_solver.d \
./lib/dlib/test/optimization.d \
./lib/dlib/test/optimization_test_functions.d \
./lib/dlib/test/parallel_for.d \
./lib/dlib/test/parse.d \
./lib/dlib/test/pipe.d \
./lib/dlib/test/pixel.d \
./lib/dlib/test/probabilistic.d \
./lib/dlib/test/pyramid_down.d \
./lib/dlib/test/queue.d \
./lib/dlib/test/rand.d \
./lib/dlib/test/ranking.d \
./lib/dlib/test/read_write_mutex.d \
./lib/dlib/test/reference_counter.d \
./lib/dlib/test/rls.d \
./lib/dlib/test/sammon.d \
./lib/dlib/test/scan_image.d \
./lib/dlib/test/sequence.d \
./lib/dlib/test/sequence_labeler.d \
./lib/dlib/test/sequence_segmenter.d \
./lib/dlib/test/serialize.d \
./lib/dlib/test/set.d \
./lib/dlib/test/sldf.d \
./lib/dlib/test/sliding_buffer.d \
./lib/dlib/test/smart_pointers.d \
./lib/dlib/test/sockets.d \
./lib/dlib/test/sockets2.d \
./lib/dlib/test/sockstreambuf.d \
./lib/dlib/test/sparse_vector.d \
./lib/dlib/test/stack.d \
./lib/dlib/test/static_map.d \
./lib/dlib/test/static_set.d \
./lib/dlib/test/statistics.d \
./lib/dlib/test/std_vector_c.d \
./lib/dlib/test/string.d \
./lib/dlib/test/svm.d \
./lib/dlib/test/svm_c_linear.d \
./lib/dlib/test/svm_c_linear_dcd.d \
./lib/dlib/test/svm_multiclass_linear.d \
./lib/dlib/test/svm_struct.d \
./lib/dlib/test/svr_linear_trainer.d \
./lib/dlib/test/symmetric_matrix_cache.d \
./lib/dlib/test/tester.d \
./lib/dlib/test/thread_pool.d \
./lib/dlib/test/threads.d \
./lib/dlib/test/timer.d \
./lib/dlib/test/tokenizer.d \
./lib/dlib/test/trust_region.d \
./lib/dlib/test/tuple.d \
./lib/dlib/test/type_safe_union.d \
./lib/dlib/test/vectorstream.d 


# Each subdirectory must supply rules for building sources it contributes
lib/dlib/test/%.o: ../lib/dlib/test/%.cpp
	@echo 'Building file: $<'
	@echo 'Invoking: GCC C++ Compiler'
	g++ -D__cplusplus=201103L -I"/home/patrick/Documents/Diplomarbeit/03_Software/04_Release/qtalearnf0/lib" -I"/home/patrick/Documents/Diplomarbeit/03_Software/04_Release/qtalearnf0/include" -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


